dataset_dir=datasets
entropy_codec=ac
distance_coding=bit_tree

#lzss
window_size=1048576
min_match_length=4
max_match_length=258
parse_mode=optimal
hash_mode=hash4

#tans
block_size=8388608
max_workers=8
