dataset_dir=datasets
entropy_codec=tans
distance_coding=bit_tree

#lzss
window_size=1048576
min_match_length=4
max_match_length=258
parse_mode=optimal
hash_mode=hash4

#tans
tans_table_mode=lazy
block_size=67108864
max_workers=1
